<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AndroidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AndroidRepository extends EntityRepository
{

    public function findAll()
    {
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Android a ORDER BY a.id ASC');
        return $query->getResult();
    }

    public function findPoint($version, $datetime)
    {
        $query = $this->_em->createQuery('SELECT f FROM AppBundle:Point f WHERE f.Android = :version AND f.date = :date ORDER BY f.date ASC');
        $query->setParameters(array('version' => $version,
            'date' => $datetime));

        return $query->getOneOrNullResult();
    }

}
