<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{

    public function findTotal()
    {
        $query = $this->_em->createQuery('SELECT count(DISTINCT p) FROM AppBundle:Projet p 
                        INNER JOIN p.Articles pa
                        WHERE p.visible = 1
                        ORDER BY p.titre');
        return $query->getSingleScalarResult();
    }

    public function findNotEmpty()
    {
        $query = $this->_em->createQuery('SELECT p FROM AppBundle:Projet p 
                        INNER JOIN p.Articles pa
                        WHERE p.visible = 1
                        ORDER BY p.titre');
        $projets = $query->getResult();

        return $projets;
    }

    public function findLastNotEmpty()
    {
        $query = $this->_em->createQuery('SELECT p FROM AppBundle:Projet p 
                        INNER JOIN p.Articles pa
                        WHERE p.visible = 1
                        ORDER BY p.created DESC');
        $projets = $query->getResult();

        return $projets;
    }

    public function listPartsByIndex($projet)
    {
        $listParts = array();
        foreach ($projet->getArticles() as $part) {
            $listParts[$part->getRang()] = $part->getArticle();
        }
        ksort($listParts);
        return $listParts;
    }

}
