<?php

namespace AppBundle\Repository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRand()
    {
        $query = $this->_em->createQuery('SELECT count(q) FROM AppBundle:Quote q ');
        $count = $query->getSingleScalarResult();

        $query = $this->_em->createQuery('SELECT q FROM AppBundle:Quote q');
        $query->setFirstResult(rand(0, $count - 1));
        $query->setMaxResults(1);
        return $query->getOneOrNullResult();
    }
}
