<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends EntityRepository
{
    public function getAllByRank($nb)
    {
        $query = $this->_em->createQuery('SELECT s FROM AppBundle:Stat s ORDER BY s.rank ASC');
        $query->setMaxResults($nb);
        return $query->getResult();
    }

}
